### ISSUE TITLE
slang depends on obsolete pcre library

### ISSUE THREAD

**Issue by fuanan-3** [hankem/S-Lang#1]
hello *,
according to https://pcre.org/, the pcre library version that slang is currently using is deprecated.

Are there plans to switch to pcre2(https://github.com/PhilipHazel/pcre2.git) or decouple pcre?

**Comment by hankem** [comment]
Thanks for raising this issue!
Note that this is _not_ the "official" S-Lang repository (see https://www.jedsoft.org/slang/download.html and https://www.jedsoft.org/snapshots/), but just a fork where I had once contributed a feature, but I'll forward the question to the S-Lang maintainer @jedsoft.

**Comment by fuanan-3** [comment]
I can't get the Maintainer progress.I guess there's a lot of modification.
@hankem 
@jedsoft

**Comment by hankem** [comment]
I forgot to update here that I had recieved the following information from @jedsoft some time ago:
> I plan to release slang 2.3.3 at the end of July or the first week of August.
> Because of that, I do not want to make any non-trivial changes.
> After 2.3.3 has been released, then I will migrate to the next version of pcre.

**Comment by jedsoft** [comment]
Hi Manfred.  I plan to release v2.3.3 soon and I want to hold off on
any large changes until after the upcoming release.  Thanks, --John

On Mon, 30 May 2022 02:26:38 -0700, fuanan-3 ***@***.***> said:

**Comment by he7850** [comment]
@jedsoft Hi, is there any progress in switching to pcre2? hope v2.3.4 can get rid of deprecated pcre

**Comment by fuanan-3** [comment]
Just decoupling BuildRequires:pcre
